### ISSUE TITLE
For github actions

### ISSUE THREAD

**Issue by marmik18** [neeldoshi7/PD#1]
This if for firebase deployment, you might need to follow a similar track but different track for your use case

`main.yml`
```
name: CI
on:
  push:
    branches: [ master ]
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-node@master
      with:
        node-version: '12'

    - name: Installing yarn
      run: npm i -g yarn
    
    - name: Installing node modules
      run: yarn install

    - name: Setting yarn ignore-engines to true
      run: yarn config set ignore-engines true

    - name: Installing node modules for firebase functions
      run: cd functions && yarn install && cd ..

    - name: Building prod
      run: yarn build --prod

    - uses: w9jds/firebase-action@master
      with:
        args: deploy
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROD_PROJECT_ID }}

```
